### ISSUE TITLE
Text color of topbar labels are almost the same color as the background.

### ISSUE THREAD

**Issue by DABRiXPERT** [KageRyo/MyWebsite#1]
As the picture shows below.
Only happens while in light mode.
![image](https://user-images.githubusercontent.com/43691523/233845283-58d0289e-43bc-4caa-9faa-cc9c089cab5a.png)

**Comment by KageRyo** [comment]
Thank you for your feedback! I understand that the text color of the topbar labels is too close to the background color, making it hard to read, especially in light mode.

To resolve this issue, I have set the website to forcibly use the dark mode.

In the future, I may also consider adding a dark/light mode toggle feature.

I hope this solves the problem you pointed out. If you have any further questions or suggestions, please feel free to share!

**Comment by KageRyo** [comment]
The dark/light mode toggle is done.
You can see #2 .
